author: ToniTang
name: OnlineStaff
main: us.rpvp.onlinestaff.OnlineStaff
description: Check whether staff are online and query it to a database available for web retrieval.
url: http://realmsofpvp.net/
version: ${project.version}

commands:
  osreload:
    usage: /osreload
    permission: onlinestaff.reload
    description: Reload the OnlineStaff configuration
    permission-message: "ยง4You don't have permission for this command."

permissions:
  onlinestaff.staff:
    description: Permission node that allows onlinestaff to execute certain group or player
    default: false