author: ToniTang
database: true
description: Check whether staff are online and query it to a database available for web retrieval.
main: us.rpvp.onlinestaff.OnlineStaff
name: OnlineStaff
url: http://realmsofpvp.net/
version: '0.1'
commands:
    osreload:
        description: Reload the OnlineStaff configuration
        usage: /osreload
        permission: onlinestaff.osreload